language: php

cache:
  directories:
    - $HOME/.chapi/cache

dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.15
  - hhvm-3.18

matrix:
  fast_finish: true

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  - composer self-update
  - composer install --prefer-source

script: ./bin/phpunit --coverage-clover=coverage.clover -c test/phpunit.xml test/

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
